development:
  adapter: postgresql
  encoding: unicode
  database: places_development
  pool: 5
  #username: postgres
  #password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: places_test
  pool: 5
  #username: postgres
  #password:
  min_messages: WARNING
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: places_production
  pool: 5
  username: postgres
  password:
  host: localhost
